### ISSUE TITLE
event.source.host throws error in on_notice during MOTD

### ISSUE THREAD

**Issue by wolfy1339** [itslukej/zirc#33]
```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wolfy1339/Python-IRC-Bot/handlers.py", line 100, in on_notice
    source = event.source.host
  File "/usr/local/lib/python3.5/dist-packages/zirc/event.py", line 91, in host
    userhost = self.split("!")[1]
IndexError: list index out of range
```

**Comment by wolfy1339** [comment]
It's caused by self.split("!")[1] where self = 'niven.freenode.net'
